---
title: "Annotated Bibliography"
format: html
editor: visual
bibliography: references.bib
---

Algorithmic Fairness: Choices, Assumptions, and Definitions: [@mitchellAlgorithmicFairnessChoices2021]

-   Summary: This article gets into how bias and inconsistency effects predictive-based decision making, which is key to the actuarial profession. Many high-stakes fields use these kinds of models to make decisions, so having an unreliable or unfair model could have very serious impacts on real people.

-   Reliability: My chosen article introduces an emerging discussion in the actuarial world: the invention of the Actuary of the Fifth Kind, who is a "critical and socially responsible financial decision maker". Social responsibility includes the concern of fairness and inconsistentcy of statistical learning models. The authors of the article claimed no financial bias in the disclosure statement, and the research was funding by Harvard-MIT Ethics and Governance of Artificial Intelligence Initiative. I view this as a reliable source, and given the department, I expect ethical research and resepct to the subject.

-   Missing Information: There are some topics in the paper I am lacking introduction knowledge on, specifically sufficiency and utility maximization. I also found that I couldn't follow some of the notation used, but the paper did not explain what some of it meant at a level I could understand. A notation guide with definitions would be very helpful.

Probabilistic Forecasting: [@gneitingProbabilisticForecasting2014]

-   Summary:

-   Reliability:

-   Missing Information:
